import { Clock3, Radio, ShieldCheck } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { OperationalAlert, PageHeading, StatePreview, StatusBadge, SurfaceCard } from "@/components/RaneevUI";

const toneFor = (status: string) => status === "sent" || status === "delivered_demo" ? "safe" as const : status === "pending" ? "warning" as const : "critical" as const;

export function AdminNotificationActivity() {
  const audits = trpc.admin.notificationAudits.useQuery(undefined, { refetchInterval: 15_000 });
  if (audits.isLoading) return <><PageHeading eyebrow="Notification activity" title="Loading protected delivery audit." description="RANEEV stores notification status separately from incident content." /><SurfaceCard tone="info" className="p-6">Loading notification audit records…</SurfaceCard></>;
  return <><PageHeading eyebrow="Notification activity" title="Review delivery outcomes without message exposure." description="This audit shows recipient role, incident reference, priority, channel, provider, read state, and delivery outcome. It deliberately omits notification message content." action={<StatusBadge tone="info" label={`${audits.data?.length ?? 0} records`} />} /><SurfaceCard tone="info" className="p-5 sm:p-6"><div className="hidden grid-cols-[0.85fr_1fr_0.7fr_0.9fr_0.8fr_1fr] gap-4 border-b border-[#d7dddc] pb-3 text-[0.65rem] font-extrabold uppercase tracking-[0.1em] text-[#60707c] lg:grid"><span>Time</span><span>Event</span><span>Recipient</span><span>Delivery</span><span>Provider</span><span>Shared context</span></div>{audits.data?.length ? audits.data.map(item => <div key={item.id} className="grid gap-2 border-b border-[#edf0ee] py-4 text-sm lg:grid-cols-[0.85fr_1fr_0.7fr_0.9fr_0.8fr_1fr] lg:gap-4"><span className="rn-mono text-xs font-semibold text-[#60707c]">{new Date(item.createdAt).toLocaleString()}</span><span><p className="font-extrabold">{item.type.replaceAll("_", " ")}</p><p className="mt-1 text-[0.65rem] font-semibold uppercase tracking-[0.08em] text-[#60707c]">{item.priority}</p></span><span className="text-xs font-semibold text-[#52626c]">{item.recipientRole}</span><span><StatusBadge tone={toneFor(item.status)} label={item.status.replaceAll("_", " ")} />{item.status === "failed" && <p className="mt-2 text-[0.65rem] font-semibold text-[#a52828]">Provider failure recorded; protected in-app status is retained.</p>}</span><span className="text-xs font-semibold text-[#52626c]">{item.provider} · {item.channel}{item.readAt ? " · read" : ""}</span><span className="text-xs font-semibold text-[#52626c]">{item.publicId ? `Incident ${item.publicId}` : "Operational notice"}</span></div>) : <p className="rounded-lg border border-dashed border-[#cad4d5] p-5 text-sm font-semibold text-[#60707c]">No notification activity has been recorded.</p>}</SurfaceCard><div className="mt-6 grid gap-4 xl:grid-cols-[1fr_0.65fr]"><OperationalAlert tone="warning" title="Privacy-preserving audit">This view intentionally excludes notification bodies, descriptions, exact locations, phone numbers, and provider credentials. It is an operational delivery audit, not an incident-content archive.</OperationalAlert><SurfaceCard tone="safe" className="p-5"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 text-[#247352]" /><div><p className="text-sm font-extrabold">Core workflow independence</p><p className="mt-1 text-xs font-medium leading-5 text-[#60707c]">Delivery failures are captured here while shared emergency actions continue.</p></div></div></SurfaceCard></div><div className="mt-6"><StatePreview compact /></div></>;
}
