import { Bot, CheckCircle2, Clock3, ShieldAlert } from "lucide-react";
import { OperationalAlert, PageHeading, StatePreview, StatusBadge, SurfaceCard } from "@/components/RaneevUI";
import { trpc } from "@/lib/trpc";

const toneFor = (status: string) => status === "succeeded" ? "safe" as const : status === "fallback" ? "warning" as const : "critical" as const;

export function AdminAiActivity() {
  const audits = trpc.admin.aiAudits.useQuery(undefined, { refetchInterval: 15_000 });
  if (audits.isLoading) return <><PageHeading eyebrow="AI activity" title="Loading protected AI audit activity." description="RANEEV records optional AI operations separately from the core incident lifecycle." /><SurfaceCard tone="info" className="p-6">Loading AI audit records…</SurfaceCard></>;
  return <><PageHeading eyebrow="AI activity" title="Review AI operations and safeguards." description="These records show optional AI execution status, duration, validation outcome, and incident reference without exposing raw prompts or private profile data." action={<StatusBadge tone="info" label={`${audits.data?.length ?? 0} records`} />} /><SurfaceCard tone="info" className="p-5 sm:p-6"><div className="hidden grid-cols-[0.8fr_0.7fr_0.9fr_0.8fr_1fr] gap-4 border-b border-[#d7dddc] pb-3 text-[0.65rem] font-extrabold uppercase tracking-[0.1em] text-[#60707c] lg:grid"><span>Time</span><span>Operation</span><span>Outcome</span><span>Duration</span><span>Shared context</span></div>{audits.data?.length ? audits.data.map(({ audit, publicId }) => <div key={audit.id} className="grid gap-2 border-b border-[#edf0ee] py-4 text-sm lg:grid-cols-[0.8fr_0.7fr_0.9fr_0.8fr_1fr] lg:gap-4"><span className="rn-mono text-xs font-semibold text-[#60707c]">{new Date(audit.createdAt).toLocaleString()}</span><span className="font-extrabold">{audit.operation.replace(/_/g, " ")}</span><span><StatusBadge tone={toneFor(audit.status)} label={audit.status} />{audit.failureCode ? <p className="mt-2 text-[0.65rem] font-semibold text-[#9a4b17]">{audit.failureCode}</p> : null}</span><span className="flex items-center gap-2 text-xs font-semibold text-[#52626c]"><Clock3 className="h-3.5 w-3.5" />{audit.durationMs} ms</span><span className="text-xs font-semibold text-[#52626c]">{publicId ? `Incident ${publicId}` : "Coordinator operational context"}{audit.modelIdentifier ? ` · ${audit.modelIdentifier}` : " · deterministic fallback"}</span></div>) : <p className="rounded-lg border border-dashed border-[#cad4d5] p-5 text-sm font-semibold text-[#60707c]">No AI activity has been recorded.</p>}</SurfaceCard><div className="mt-6 grid gap-4 xl:grid-cols-[1fr_0.55fr]"><OperationalAlert tone="warning" title="AI is operational support only">AI output is validated, auditable, and optional. It does not assign responders, change incident status, approve verification, or replace professional emergency judgement.</OperationalAlert><SurfaceCard tone="safe" className="p-5"><div className="flex items-start gap-3"><CheckCircle2 className="mt-0.5 h-5 w-5 text-[#247352]" /><div><p className="text-sm font-extrabold">Core workflow independence</p><p className="mt-1 text-xs font-medium leading-5 text-[#60707c]">Failed or delayed AI jobs remain visible here while emergency operations continue.</p></div></div></SurfaceCard></div><div className="mt-6"><StatePreview compact /></div></>;
}
