import { useCallback, useEffect, useMemo, useState } from "react";
import { Link, useLocation } from "wouter";
import { Activity, CheckCircle2, Clock3, MapPin, Navigation, Radio, ShieldCheck, TriangleAlert } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { EmergencyMap } from "@/components/EmergencyMap";
import { AiIncidentInsight } from "@/components/AiIncidentInsight";
import type { RouteMetrics } from "@/lib/maps/contracts";
import { trpc } from "@/lib/trpc";
import { BackLink, ConsoleShell, Metric, OperationalAlert, PageHeading, StatePreview, StatusBadge, SurfaceCard } from "@/components/RaneevUI";

type DeviceCoordinates = { lat: number; lng: number };

function emergencyLabel(type: string) { return type.replace(/_/g, " ").replace(/\b\w/g, letter => letter.toUpperCase()); }
function formatDistance(meters: number) { return meters >= 1000 ? `${(meters / 1000).toFixed(1)} km` : `${meters} m`; }

function useDeviceCoordinates() {
  const [coordinates, setCoordinates] = useState<DeviceCoordinates | null>(null);
  const requestCoordinates = useCallback(() => new Promise<DeviceCoordinates>((resolve, reject) => {
    if (!navigator.geolocation) return reject(new Error("This device cannot provide its current location."));
    navigator.geolocation.getCurrentPosition(position => {
      const next = { lat: position.coords.latitude, lng: position.coords.longitude };
      setCoordinates(next);
      resolve(next);
    }, () => reject(new Error("Allow location access to coordinate a nearby response.")), { enableHighAccuracy: true, timeout: 12_000, maximumAge: 30_000 });
  }), []);
  return { coordinates, requestCoordinates };
}

export function VolunteerMode({ page }: { page?: string }) {
  const view = page ?? "home";
  const readiness = trpc.volunteer.readiness.useQuery(undefined, { refetchInterval: 10_000 });
  const shouldVerify = readiness.data?.profileStatus === "pending_verification";
  const content = shouldVerify && view !== "verification" ? <VolunteerVerification /> : view === "verification" ? <VolunteerVerification /> : view === "availability" ? <VolunteerAvailability /> : view === "nearby" ? <VolunteerNearby /> : view === "accept" ? <VolunteerAcceptRedirect /> : view === "active" || view === "assist" ? <VolunteerActive /> : view === "history" ? <VolunteerHistory /> : view === "profile" ? <VolunteerProfile /> : <VolunteerHome />;
  return <ConsoleShell role="volunteer">{content}</ConsoleShell>;
}

function VolunteerAcceptRedirect() {
  const [, setLocation] = useLocation();
  useEffect(() => { setLocation("/volunteer/nearby"); }, [setLocation]);
  return <VolunteerLoading title="Opening nearby emergency review." />;
}

function VolunteerVerification() {
  const [, setLocation] = useLocation();
  const utils = trpc.useUtils();
  const readiness = trpc.volunteer.readiness.useQuery();
  const verify = trpc.volunteer.completeDevelopmentVerification.useMutation({ onSuccess: async () => { await utils.volunteer.readiness.invalidate(); toast.success("Verification approved for this development workspace."); setLocation("/volunteer"); } });
  if (readiness.isLoading) return <VolunteerLoading title="Checking verification status." />;
  const verified = readiness.data?.profileStatus === "active";
  return <><PageHeading eyebrow="Volunteer verification" title={verified ? "Your responder profile is verified." : "Complete responder verification."} description={verified ? "You can now set availability and receive shared emergency requests." : "Identity and readiness are reviewed before incident details or matching become available."} action={<StatusBadge tone={verified ? "safe" : "warning"} label={verified ? "Verified" : "Review pending"} />} /><div className="grid gap-6 xl:grid-cols-[1fr_0.58fr]"><SurfaceCard tone={verified ? "safe" : "warning"} className="p-6"><div className="flex items-start gap-4"><span className={`flex h-12 w-12 shrink-0 items-center justify-center rounded-xl ${verified ? "bg-[#e8f5ed] text-[#247352]" : "bg-[#fff3dc] text-[#b86d0a]"}`}><ShieldCheck className="h-6 w-6" /></span><div><h2 className="text-2xl font-extrabold tracking-[-0.05em]">{verified ? "Operational credentials confirmed" : "Verification before dispatch"}</h2><p className="mt-2 text-sm font-medium leading-6 text-[#52626c]">RANEEV withholds exact citizen location and acceptance controls until a Volunteer is verified.</p></div></div><div className="mt-6 space-y-3 border-y border-[#edf0ee] py-3">{[["Identity review", verified ? "Approved" : "Awaiting review"], ["Response safety acknowledgement", "Recorded"], ["Location consent", "Requested when available"]].map(([label, status]) => <div key={label} className="flex items-center justify-between gap-4 py-2"><p className="text-sm font-extrabold">{label}</p><span className="text-xs font-bold text-[#60707c]">{status}</span></div>)}</div>{verified ? <Link href="/volunteer/availability" className="rn-focus mt-6 inline-flex min-h-12 items-center rounded-lg bg-[#0e4e78] px-5 text-sm font-extrabold text-white">Go to availability</Link> : <Button disabled={verify.isPending} onClick={() => verify.mutate()} className="rn-touch mt-6 w-full bg-[#0e4e78] font-extrabold hover:bg-[#0b3e61]">Complete development verification</Button>}</SurfaceCard><div className="space-y-4"><OperationalAlert tone="warning" title="Production safeguard">Development approval is enabled only in this local workflow. Production verification requires an authorized coordinator review.</OperationalAlert><StatePreview compact /></div></div></>;
}

function VolunteerHome() {
  const readiness = trpc.volunteer.readiness.useQuery();
  const active = trpc.volunteer.activeIncident.useQuery(undefined, { refetchInterval: 8_000 });
  if (readiness.isLoading || active.isLoading) return <VolunteerLoading title="Loading response readiness." />;
  const available = readiness.data?.availability === "available";
  return <><PageHeading eyebrow="Volunteer dashboard" title={active.data ? "You have an active response." : "Your response readiness."} description={active.data ? "Continue the assigned Citizen emergency without opening a duplicate case." : "Set availability and share a current location before nearby Citizen-created emergencies are listed."} action={<StatusBadge tone={active.data ? "critical" : available ? "safe" : "neutral"} label={active.data ? "Active response" : available ? "Available" : "Offline"} />} /><div className="grid gap-5 md:grid-cols-3"><Metric label="Verification" value={readiness.data?.profileStatus === "active" ? "Active" : "Pending"} sub="Required for dispatch" tone={readiness.data?.profileStatus === "active" ? "safe" : "warning"} /><Metric label="Availability" value={readiness.data?.availability ?? "Offline"} sub="Server-confirmed state" tone={available ? "safe" : "info"} /><Metric label="Assignment" value={active.data ? active.data.publicId : "None"} sub={active.data ? emergencyLabel(active.data.emergencyType) : "No active incident"} tone={active.data ? "critical" : "info"} /></div><div className="mt-6 grid gap-6 xl:grid-cols-[1.1fr_0.9fr]"><SurfaceCard tone={active.data ? "critical" : available ? "safe" : "info"} className="p-6"><div className="flex items-start justify-between"><div><StatusBadge tone={active.data ? "critical" : available ? "safe" : "neutral"} label={active.data ? "Assigned" : available ? "Ready for matching" : "Not receiving alerts"} /><h2 className="mt-4 text-2xl font-extrabold tracking-[-0.05em]">{active.data ? `Continue ${active.data.publicId}` : available ? "You can receive nearby requests." : "Go available when you are ready."}</h2><p className="mt-2 text-sm font-medium leading-6 text-[#52626c]">{active.data ? "This is the same incident record created by the Citizen." : "Exact incident location stays restricted until a verified Volunteer accepts a shared request."}</p></div><Radio className="h-8 w-8 text-[#0e4e78]" /></div><div className="mt-6 flex flex-wrap gap-3">{active.data ? <Link href="/volunteer/active" className="rn-focus flex min-h-11 items-center rounded-lg bg-[#d83232] px-4 text-sm font-extrabold text-white">Open active response</Link> : <><Link href="/volunteer/availability" className="rn-focus flex min-h-11 items-center rounded-lg bg-[#0e4e78] px-4 text-sm font-extrabold text-white">GO AVAILABLE</Link>{available && <Link href="/volunteer/nearby" className="rn-focus flex min-h-11 items-center rounded-lg border border-[#cbd5d6] bg-white px-4 text-sm font-extrabold text-[#0e4e78]">View nearby emergencies</Link>}</>}</div></SurfaceCard><OperationalAlert tone="warning" title="Never travel beyond your training">Accept only incidents you can safely support. Professional emergency services remain the priority.</OperationalAlert></div></>;
}

function VolunteerAvailability() {
  const [, setLocation] = useLocation();
  const utils = trpc.useUtils();
  const readiness = trpc.volunteer.readiness.useQuery();
  const { coordinates, requestCoordinates } = useDeviceCoordinates();
  const availability = trpc.volunteer.setAvailability.useMutation({ onSuccess: async state => { await utils.volunteer.readiness.invalidate(); toast.success(state.availability === "available" ? "You are now available for nearby emergency matching." : "Availability updated."); if (state.availability === "available") setLocation("/volunteer/nearby"); } });
  const goAvailable = async () => { try { const position = await requestCoordinates(); await availability.mutateAsync({ availability: "available", latitude: position.lat, longitude: position.lng }); } catch (error) { toast.error(error instanceof Error ? error.message : "Location could not be updated."); } };
  if (readiness.isLoading) return <VolunteerLoading title="Loading availability controls." />;
  const isAvailable = readiness.data?.availability === "available";
  return <><PageHeading eyebrow="Availability" title="Control when you can respond." description="Availability is server-confirmed and requires current device location before RANEEV exposes nearby Citizen-created emergency requests." action={<StatusBadge tone={isAvailable ? "safe" : "neutral"} label={isAvailable ? "Available" : "Offline"} />} /><div className="grid gap-6 xl:grid-cols-[0.8fr_1.2fr]"><SurfaceCard tone={isAvailable ? "safe" : "info"} className="p-6"><StatusBadge tone={isAvailable ? "safe" : "neutral"} label={isAvailable ? "Currently available" : "Currently offline"} /><h2 className="mt-4 text-2xl font-extrabold tracking-[-0.05em]">{isAvailable ? "Matching is enabled." : "Share location to go available."}</h2><p className="mt-2 text-sm font-medium leading-6 text-[#60707c]">{coordinates ? `Device location captured at ${coordinates.lat.toFixed(4)}, ${coordinates.lng.toFixed(4)}.` : "Location remains device-controlled and is used only for authorized response matching."}</p><div className="mt-6 flex flex-col gap-3 sm:flex-row"><Button disabled={availability.isPending || isAvailable} onClick={goAvailable} className="rn-touch flex-1 bg-[#0e4e78] font-extrabold hover:bg-[#0b3e61]">GO AVAILABLE</Button><Button disabled={availability.isPending || !isAvailable} onClick={() => availability.mutate({ availability: "offline" })} variant="outline" className="rn-touch flex-1 border-[#cbd5d6] font-extrabold text-[#43535e]">Go offline</Button></div></SurfaceCard><SurfaceCard tone="info" className="p-6"><p className="rn-eyebrow">Readiness checks</p><div className="mt-4 space-y-3">{[["Volunteer verification", readiness.data?.profileStatus === "active" ? "Approved" : "Pending"], ["Current location", isAvailable ? "Current" : "Required"], ["Active assignment", "None"], ["Incident visibility", "Restricted until assignment"]].map(([label, status]) => <div key={label} className="flex items-center justify-between border-b border-[#edf0ee] py-3"><p className="text-sm font-extrabold">{label}</p><span className="text-xs font-bold text-[#60707c]">{status}</span></div>)}</div></SurfaceCard></div></>;
}

function VolunteerNearby() {
  const [, setLocation] = useLocation();
  const utils = trpc.useUtils();
  const readiness = trpc.volunteer.readiness.useQuery();
  const nearby = trpc.volunteer.nearbyIncidents.useQuery(undefined, { enabled: readiness.data?.availability === "available", refetchInterval: 6_000 });
  const accept = trpc.volunteer.accept.useMutation({ onSuccess: async () => { await Promise.all([utils.volunteer.activeIncident.invalidate(), utils.volunteer.nearbyIncidents.invalidate(), utils.volunteer.readiness.invalidate()]); toast.success("Emergency request accepted. Exact route is now authorized."); setLocation("/volunteer/active"); } });
  if (readiness.isLoading || nearby.isLoading) return <VolunteerLoading title="Checking nearby emergency requests." />;
  if (readiness.data?.availability !== "available") return <><PageHeading eyebrow="Nearby emergencies" title="Go available to receive requests." description="Current device location and verified availability are required before RANEEV can offer nearby shared incidents." /><SurfaceCard tone="warning" className="p-6"><p className="text-lg font-extrabold">Matching is paused while you are offline.</p><Link href="/volunteer/availability" className="rn-focus mt-5 inline-flex min-h-11 items-center rounded-lg bg-[#0e4e78] px-4 text-sm font-extrabold text-white">Go to availability</Link></SurfaceCard></>;
  if (nearby.error) return <><PageHeading eyebrow="Nearby emergencies" title="Matching is temporarily unavailable." description="Your availability remains protected. Refresh or return to the dashboard if this issue continues." /><OperationalAlert tone="warning" title="Unable to load nearby requests">{nearby.error.message}</OperationalAlert></>;
  return <><PageHeading eyebrow="Nearby emergency" title={nearby.data?.length ? "Citizen requests available to review." : "No nearby requests right now."} description={nearby.data?.length ? "Before acceptance, RANEEV limits information to distance, category, and safe response assessment." : "Keep availability active to receive new Citizen-created requests."} action={nearby.data?.length ? <StatusBadge tone="critical" label={`${nearby.data.length} request${nearby.data.length === 1 ? "" : "s"}`} /> : <StatusBadge tone="safe" label="Listening" />} />{nearby.data?.length ? <div className="grid gap-4 xl:grid-cols-2">{nearby.data.map(incident => <SurfaceCard key={incident.publicId} tone="critical" className="p-6"><div className="flex items-center justify-between gap-4"><StatusBadge tone="critical" label={emergencyLabel(incident.emergencyType)} /><span className="rn-mono text-xs font-semibold text-[#60707c]">{incident.publicId}</span></div><h2 className="mt-5 text-2xl font-extrabold tracking-[-0.05em]">{formatDistance(incident.distanceMeters)} away</h2><p className="mt-2 text-sm font-medium leading-6 text-[#52626c]">{incident.responseArea}. Exact location and navigation remain protected until acceptance.</p><div className="mt-5 flex items-center justify-between border-y border-[#edf0ee] py-4"><span className="text-xs font-bold text-[#60707c]">Request age</span><span className="text-sm font-extrabold">{Math.max(1, Math.round((Date.now() - new Date(incident.createdAt).getTime()) / 60_000))} min</span></div><Button disabled={accept.isPending} onClick={() => accept.mutate({ publicId: incident.publicId })} className="rn-touch mt-5 w-full bg-[#0e4e78] font-extrabold hover:bg-[#0b3e61]">Accept response request</Button></SurfaceCard>)}</div> : <SurfaceCard tone="safe" className="p-8 text-center"><CheckCircle2 className="mx-auto h-9 w-9 text-[#247352]" /><h2 className="mt-4 text-xl font-extrabold">You are available and within range.</h2><p className="mx-auto mt-2 max-w-md text-sm font-medium leading-6 text-[#60707c]">No active Citizen requests match your current response area.</p></SurfaceCard>}</>;
}

function VolunteerActive() {
  const [, setLocation] = useLocation();
  const utils = trpc.useUtils();
  const { coordinates, requestCoordinates } = useDeviceCoordinates();
  const active = trpc.volunteer.activeIncident.useQuery(undefined, { refetchInterval: 4_000 });
  const incidentInput = useMemo(() => ({ publicId: active.data?.publicId ?? "pending" }), [active.data?.publicId]);
  const mapSnapshot = trpc.incidents.mapSnapshot.useQuery(incidentInput, { enabled: Boolean(active.data?.publicId), refetchInterval: 3_000 });
  const [metrics, setMetrics] = useState<RouteMetrics | null>(null);
  const startRoute = trpc.volunteer.startRoute.useMutation({ onSuccess: () => utils.volunteer.activeIncident.invalidate() });
  const arrive = trpc.volunteer.arrive.useMutation({ onSuccess: () => utils.volunteer.activeIncident.invalidate() });
  const assist = trpc.volunteer.beginAssistance.useMutation({ onSuccess: () => utils.volunteer.activeIncident.invalidate() });
  const resolve = trpc.volunteer.resolve.useMutation({ onSuccess: async () => { await Promise.all([utils.volunteer.activeIncident.invalidate(), utils.volunteer.readiness.invalidate(), utils.incidents.mine.invalidate()]); toast.success("Shared incident resolved."); setLocation("/volunteer/history"); } });
  const updateLocation = trpc.volunteer.updateLocation.useMutation({ onSuccess: () => { utils.incidents.mapSnapshot.invalidate(incidentInput); toast.success("Responder position updated for the active incident."); } });
  const refreshPosition = async () => { if (!active.data) return; try { const position = await requestCoordinates(); await updateLocation.mutateAsync({ publicId: active.data.publicId, latitude: position.lat, longitude: position.lng }); } catch (error) { toast.error(error instanceof Error ? error.message : "Responder position could not be updated."); } };
  if (active.isLoading || (active.data && mapSnapshot.isLoading)) return <VolunteerLoading title="Loading the assigned emergency." />;
  if (!active.data) return <><PageHeading eyebrow="Active response" title="No active assignment." description="Accepted Citizen requests appear here with the authorized route, live map, and response controls." /><SurfaceCard tone="info" className="p-7"><Link href="/volunteer/nearby" className="rn-focus inline-flex min-h-11 items-center rounded-lg bg-[#0e4e78] px-4 text-sm font-extrabold text-white">View nearby emergencies</Link></SurfaceCard></>;
  const incident = active.data;
  const snapshot = mapSnapshot.data;
  const mapData = snapshot ? { incident: { id: incident.publicId, kind: "incident" as const, title: "Citizen emergency", position: { lat: incident.latitudeE6 / 1_000_000, lng: incident.longitudeE6 / 1_000_000 } }, responder: snapshot.responder ? { id: `responder-${snapshot.responder.userId}`, kind: "responder" as const, title: "Your current position", position: { lat: snapshot.responder.latitude, lng: snapshot.responder.longitude } } : undefined, currentLocation: coordinates ? { id: "volunteer-device", kind: "current" as const, title: "Your device", position: coordinates } : undefined } : null;
  const action = incident.status === "accepted" ? { label: "Start navigation", run: () => startRoute.mutate({ publicId: incident.publicId }) } : incident.status === "en_route" ? { label: "Mark as arrived", run: () => arrive.mutate({ publicId: incident.publicId }) } : incident.status === "arrived" ? { label: "Begin assistance", run: () => assist.mutate({ publicId: incident.publicId }) } : { label: "Resolve incident", run: () => resolve.mutate({ publicId: incident.publicId }) };
  const pending = startRoute.isPending || arrive.isPending || assist.isPending || resolve.isPending;
  return <><PageHeading eyebrow="Active response" title={incident.status === "assisting" ? "Assist with care." : incident.status === "arrived" ? "You have arrived." : "Navigate with care."} description="This screen is operating on the single protected incident created by the Citizen. Your location sharing and route are limited to this assignment." action={<StatusBadge tone={incident.status === "assisting" ? "warning" : "critical"} label={incident.status.replace(/_/g, " ")} />} /><div className="grid gap-6 2xl:grid-cols-[1.2fr_0.8fr]">{mapData ? <EmergencyMap data={mapData} onRouteMetrics={setMetrics} className="min-h-[32rem]" /> : <SurfaceCard tone="warning" className="p-6">Map data is loading for this assigned response.</SurfaceCard>}<div className="space-y-4"><SurfaceCard tone="critical" className="p-6"><p className="rn-eyebrow">{incident.publicId}</p><h2 className="mt-2 text-2xl font-extrabold tracking-[-0.05em]">{metrics ? `${formatDistance(metrics.distanceMeters)} · ${Math.max(1, Math.round(metrics.durationSeconds / 60))} min` : "Calculating authorized route"}</h2><p className="mt-2 text-sm font-medium leading-6 text-[#52626c]">{emergencyLabel(incident.emergencyType)} · {incident.locationLabel}</p><div className="mt-5 grid gap-2"><Button disabled={pending} onClick={action.run} className="rn-touch w-full bg-[#0e4e78] font-extrabold hover:bg-[#0b3e61]">{action.label}</Button>{["accepted", "en_route"].includes(incident.status) && <Button disabled={updateLocation.isPending} onClick={refreshPosition} variant="outline" className="rn-touch w-full border-[#0e4e78] font-extrabold text-[#0e4e78]">Update my live position</Button>}<Button onClick={() => window.open(`https://www.google.com/maps/dir/?api=1&destination=${incident.latitudeE6 / 1_000_000},${incident.longitudeE6 / 1_000_000}`, "_blank", "noopener,noreferrer")} variant="outline" className="rn-touch w-full border-[#cbd5d6] font-extrabold text-[#0e4e78]"><Navigation className="mr-2 h-4 w-4" />Open navigation</Button></div></SurfaceCard><AiIncidentInsight publicId={incident.publicId} compact /><OperationalAlert tone="info" title="Location sharing is scoped">Your live position is available only to the assigned incident and ends when the response resolves.</OperationalAlert></div></div></>;
}

function VolunteerHistory() {
  const history = trpc.incidents.mine.useQuery();
  if (history.isLoading) return <VolunteerLoading title="Loading response history." />;
  const resolved = (history.data ?? []).filter(incident => incident.status === "resolved");
  return <><PageHeading eyebrow="Response history" title="Your completed shared responses." description="Every record is a resolved Citizen-created incident assigned to your Volunteer account." action={<StatusBadge tone="safe" label={`${resolved.length} resolved`} />} /><div className="grid gap-6 xl:grid-cols-[1fr_0.45fr]"><SurfaceCard tone="safe" className="p-6">{resolved.length ? resolved.map(incident => <div key={incident.publicId} className="flex items-center justify-between gap-4 border-b border-[#edf0ee] py-4 last:border-b-0"><div><p className="text-sm font-extrabold">{emergencyLabel(incident.emergencyType)}</p><p className="mt-1 text-xs font-semibold text-[#60707c]">{incident.publicId} · {new Date(incident.resolvedAt ?? incident.updatedAt).toLocaleString()}</p></div><StatusBadge tone="safe" label="Resolved" /></div>) : <p className="text-sm font-medium text-[#60707c]">Resolved Citizen requests assigned to you will appear here.</p>}</SurfaceCard><Metric label="Completed responses" value={String(resolved.length)} sub="Shared incident records" tone="safe" /></div></>;
}

function VolunteerProfile() {
  const readiness = trpc.volunteer.readiness.useQuery();
  if (readiness.isLoading) return <VolunteerLoading title="Loading volunteer profile." />;
  const verified = readiness.data?.profileStatus === "active";
  return <><PageHeading eyebrow="Verification and profile" title="Your responder credentials." description="Verification and availability are enforced on the server before matching or route access." action={<StatusBadge tone={verified ? "safe" : "warning"} label={verified ? "Verified" : "Pending"} />} /><div className="grid gap-6 xl:grid-cols-[1fr_0.55fr]"><SurfaceCard tone={verified ? "safe" : "warning"} className="p-6"><p className="text-xl font-extrabold">Volunteer responder</p><p className="mt-1 text-sm font-semibold text-[#60707c]">Availability: {readiness.data?.availability ?? "offline"}</p><div className="mt-6 grid gap-3 sm:grid-cols-3">{[["Identity", verified ? "Approved" : "Pending"], ["Location readiness", readiness.data?.latitudeE6 ? "Current" : "Not shared"], ["Response profile", verified ? "Active" : "Restricted"]].map(([label, status]) => <div key={label} className="rounded-lg bg-[#f2faf5] p-4"><p className="text-xs font-extrabold text-[#43535e]">{label}</p><p className="mt-2 text-sm font-extrabold text-[#247352]">{status}</p></div>)}</div></SurfaceCard><OperationalAlert tone="info" title="Document privacy">Verification records remain server protected. Only approved Volunteers receive assignment and location access.</OperationalAlert></div></>;
}

function VolunteerLoading({ title }: { title: string }) { return <div><PageHeading eyebrow="Volunteer Mode" title={title} description="RANEEV is retrieving the latest protected response information." /><SurfaceCard tone="info" className="p-6"><div className="flex items-center gap-3"><Activity className="h-5 w-5 animate-pulse text-[#0e4e78]" /><span className="text-sm font-extrabold">Loading verified response data…</span></div></SurfaceCard></div>; }
